### ISSUE TITLE
Newtonsoft dependencies with FM 3.0.17 with Microsoft.NET.sdk.Functions 1.0.30-beta2 not compiling

### ISSUE THREAD

**Issue by davidjsteele** [JamesRandall/FunctionMonkey#100]
Hi James, 

Viewing issue https://github.com/JamesRandall/FunctionMonkey/issues/8, this seems to have reared its head again.  Using FM 3.0.17 with Microsoft.NET.sdk.Functions 1.0.30-beta2 and when i introduce a [JsonProperty] onto a model i receieve below exception.

`13>Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621)
13>   at System.ModuleHandle.ResolveType(RuntimeModule module, Int32 typeToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount, ObjectHandleOnStack type)
13>   at System.ModuleHandle.ResolveTypeHandleInternal(RuntimeModule module, Int32 typeToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
13>   at System.Reflection.RuntimeModule.ResolveType(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments)
13>   at System.Reflection.CustomAttribute.FilterCustomAttributeRecord(CustomAttributeRecord caRecord, MetadataImport scope, Assembly& lastAptcaOkAssembly, RuntimeModule decoratedModule, MetadataToken decoratedToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, Object[] attributes, IList derivedAttributes, RuntimeType& attributeType, IRuntimeMethodInfo& ctor, Boolean& ctorHasParameters, Boolean& isVarArg)
13>   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType, Boolean mustBeInheritable, IList derivedAttributes)
13>   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimePropertyInfo property, RuntimeType caType)
13>   at System.Attribute.InternalGetCustomAttributes(PropertyInfo element, Type type, Boolean inherit)`

_Originally posted by @davidjsteele in https://github.com/JamesRandall/FunctionMonkey/issues/8#issuecomment-547636776_

**Comment by davidjsteele** [comment]
Again caused by refit dependency
