### ISSUE TITLE
FunctionMonkey.Compiler errors when assembly refers to BigInteger

### ISSUE THREAD

**Issue by tonesandtones** [JamesRandall/FunctionMonkey#11]
Self-contained reproducible solution at this commit: https://github.com/tonesandtones/KnockKnock/commit/fa2620681661205dfea1844ef074d731a4498971

Built with dotnet core SDK 2.1.402
Az function project targetting netcoreapp2.0
FunctionMonkey 0.13.0-beta000
FunctionMonkey.Compiler 0.13.2-beta000

```
2>Unhandled Exception: FunctionMonkey.ConfigurationException: CS0433:The type 'StreamReader' exists in both 'System.Runtime.Extensions, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' and 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' SourceFile([1367..1379))CS0433:The type 'StreamReader' exists in both 'System.Runtime.Extensions, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' and 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' SourceFile([1393..1405))CS0433:The type 'StreamReader' exists in both 'System.Runtime.Extensions, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' and 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' SourceFile([1147..1159))
2>   at FunctionMonkey.Compiler.Implementation.AssemblyCompiler.CompileAssembly(IReadOnlyCollection`1 syntaxTrees, IReadOnlyCollection`1 externalAssemblies, OpenApiOutputModel openApiOutputModel, String outputBinaryFolder, String outputAssemblyName, String assemblyNamespace)
2>   at FunctionMonkey.Compiler.Implementation.FunctionCompiler.Compile() in D:\wip\myOpenSource\functionMonkey\Source\FunctionMonkey.Compiler\Implementation\FunctionCompiler.cs:line 86
2>   at FunctionMonkey.Compiler.Program.Main(String[] args) in D:\wip\myOpenSource\functionMonkey\Source\FunctionMonkey.Compiler\Program.cs:line 45
2>C:\Users\******\.nuget\packages\functionmonkey.compiler\0.13.2-beta000\build\netstandard1.0\FunctionMonkey.Compiler.targets(11,5): error MSB3073: The command "dotnet "C:\Users\anthony\.nuget\packages\functionmonkey.compiler\0.13.2-beta000\build\netstandard1.0\..\..\tools\netcoreapp2.0/FunctionMonkey.Compiler.dll" "C:\projects\readify\KnockKnock2\KnockKnock.Api.Function\bin\Debug\netstandard2.0\bin\KnockKnock.Api.Function.dll"" exited with code -532462766.
2>Done building project "KnockKnock.Api.Function.csproj" -- FAILED.
```

**Comment by JamesRandall** [comment]
Thanks for reporting this and the sample - super useful to me, would have been very hard to pin down without a self contained example. Its addressed in v0.14.0 available on NuGet now.

Thanks again!
