### ISSUE TITLE
Error when upgrading to 0.18

### ISSUE THREAD

**Issue by shep1987** [JamesRandall/FunctionMonkey#20]
Sorry James,

Get this when i upgrade to latest 0.18, rolling back to 0.17 works.

Let me know if you need anything else to help debug

```
1>Unhandled Exception: FunctionMonkey.ConfigurationException: CS7036:There is no argument given that corresponds to the required formal parameter 'serializer' of 'HelloWorld.CreateResponse(int, object, ISerializer)' SourceFile([3492..3506))
1>   at FunctionMonkey.Compiler.Implementation.AssemblyCompiler.CompileAssembly(IReadOnlyCollection`1 syntaxTrees, IReadOnlyCollection`1 externalAssemblyLocations, OpenApiOutputModel openApiOutputModel, String outputBinaryFolder, String outputAssemblyName, String assemblyNamespace, TargetEnum target)
1>   at FunctionMonkey.Compiler.Implementation.FunctionCompiler.Compile() in /Users/jamesrandall/code/myOpenSource/functionMonkey/Source/FunctionMonkey.Compiler/Implementation/FunctionCompiler.cs:line 94
1>   at FunctionMonkey.Compiler.Program.Main(String[] args) in /Users/jamesrandall/code/myOpenSource/functionMonkey/Source/FunctionMonkey.Compiler/Program.cs:line 47
1>C:\Users\xxx\.nuget\packages\functionmonkey.compiler\0.18.2-beta000\build\netstandard1.0\FunctionMonkey.Compiler.targets(19,5): error MSB3073: The command "dotnet "C:\Users\xxx\.nuget\packages\functionmonkey.compiler\0.18.2-beta000\build\netstandard1.0\..\..\tools\netcoreapp2.1/FunctionMonkey.Compiler.dll" "C:\_Git\NXG\OnBoarding.Functions\OnBoarding.Functions\bin\Debug\netstandard2.0\bin\OnBoarding.Functions.dll"" exited with code -532462766.
```

**Comment by JamesRandall** [comment]
Thanks for reporting - I've just uploaded v0.18.5 of FunctionMonkey.Compiler to NuGet that should fix this. Be grateful if you could let me know if it does! I'd missed a refactoring in one of the Handlebars templates (which oaren't syntax checked until compiled by Roslyn).

I've got some integration tests on the way ahead of v1.0.0 that should pick up these things.
