### ISSUE TITLE
Compiler error

### ISSUE THREAD

**Issue by nugosu** [JamesRandall/FunctionMonkey#28]
1>------ Build started: Project: EML, Configuration: Debug Any CPU ------
1>C:\Users\melgs\.nuget\packages\microsoft.net.sdk.functions\1.0.24\build\netstandard1.0\Microsoft.NET.Sdk.Functions.props(38,3): warning MSB4011: "C:\Users\melgs\.nuget\packages\microsoft.azure.webjobs.script.extensionsmetadatagenerator\1.0.1\build\Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator.props" cannot be imported again. It was already imported at "C:\GIT\myAzureFunction\EML\EML\obj\EML.csproj.nuget.g.props (17,5)". This is most likely a build authoring error. This subsequent import will be ignored. [C:\GIT\myAzureFunction\EML\EML\EML.csproj]
1>C:\Users\melgs\.nuget\packages\microsoft.net.sdk.functions\1.0.24\build\netstandard1.0\Microsoft.NET.Sdk.Functions.targets(45,3): warning MSB4011: "C:\Users\melgs\.nuget\packages\microsoft.azure.webjobs.script.extensionsmetadatagenerator\1.0.1\build\Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator.targets" cannot be imported again. It was already imported at "C:\GIT\myAzureFunction\EML\EML\obj\EML.csproj.nuget.g.targets (9,5)". This is most likely a build authoring error. This subsequent import will be ignored. [C:\GIT\myAzureFunction\EML\EML\EML.csproj]
1>C:\GIT\myAzureFunction\EML\EML\EML.csproj : warning NU1701: Package 'Microsoft.Azure.WebJobs.Extensions.DocumentDB 1.1.0' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may not be fully compatible with your project.
1>EML -> C:\GIT\myAzureFunction\EML\EML\bin\Debug\netcoreapp2.1\bin\EML.dll
1>
1>Unhandled Exception: FunctionMonkey.TypeLoadingException: ReflectionTypeLoadException: Unable to load one or more of the requested types.
1>Could not load file or assembly 'Microsoft.Azure.DocumentDB.Core, Version=2.1.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621)
1>Unable to load types:
1>    AccountManagement.ServiceTestRequest
1>    AccountManagement.FileAccess
1>    AccountManagement.FileIOPermissionAccess
1>    AccountManagement.ServiceTestResponse
1>    AccountManagement.AutoMapperTestResult
1>    AccountManagement.DtoTestResult
1>    AccountManagement.FailedTestTypes
1>    AccountManagement.FilePermissionTestResult
1>    AccountManagement.ServiceTestResult
1>    AccountManagement.ServicePingResult
1>    AccountManagement.TestResultBase
1>    AccountManagement.ExternalRequest
1>    AccountManagement.SecurityRequest
1>    AccountManagement.GetAccountDetailsRequest
1>    AccountManagement.ActivatePlasticCardRequest
1>    AccountManagement.DeactivatePlasticCardRequest
1>    AccountManagement.DeactivateCardRequest
1>    AccountManagement.GetAccountStatusRequest
1>    AccountManagement.GetAccountDipRequest
1>    AccountManagement.UpdateAccountDetailsRequest
1>    AccountManagement.CreateAccountRequest
1>    AccountManagement.GetMobileWalletDataRequest
1>    AccountManagement.GetApplePayWalletDataRequest
1>    AccountManagement.GetMobileWalletTokensRequest
1>    AccountManagement.GetAccountFreeFieldDefinitionsRequest
1>    AccountManagement.UpdateAccountFreeFieldsRequest
1>    AccountManagement.GetAccountFreeFieldsRequest
1>    AccountManagement.ActivateCardRequest
1>    AccountManagement.ExternalAccountIdentifier
1>    AccountManagement.DetailFlags
1>    AccountManagement.ClientDetails
1>    AccountManagement.UserCredentials
1>    AccountManagement.WalletProvider
1>    AccountManagement.FreeFieldData
1>    AccountManagement.FreeFieldName
1>    AccountManagement.FreeFieldType
1>    AccountManagement.BaseResponse
1>    AccountManagement.ErrorCode
1>    AccountManagement.GetAccountDetailsResponse
1>    AccountManagement.ActivatePlasticCardResponse
1>    AccountManagement.DeactivatePlasticCardResponse
1>    AccountManagement.DeactivateCardResponse
1>    AccountManagement.GetAccountStatusResponse
1>    AccountManagement.GetAccountDipResponse
1>    AccountManagement.UpdateAccountDetailsResponse
1>    AccountManagement.CreateAccountResponse
1>    AccountManagement.GetMobileWalletDataResponse
1>    AccountManagement.GetApplePayWalletDataResponse
1>    AccountManagement.GetMobileWalletTokensResponse
1>    AccountManagement.GetAccountFreeFieldDefinitionsResponse
1>    AccountManagement.UpdateAccountFreeFieldsResponse
1>    AccountManagement.GetAccountFreeFieldsResponse
1>    AccountManagement.ActivateCardResponse
1>    AccountManagement.AccountDetails
1>    AccountManagement.CardState
1>    AccountManagement.ProductType
1>    AccountManagement.Provider
1>    AccountManagement.Token
1>    AccountManagement.Device
1>    AccountManagement.TokenStatus
1>    AccountManagement.TokenisationDecision
1>    AccountManagement.ProvisioningStatus
1>    AccountManagement.StorageTechnology
1>    AccountManagement.Suspender
1>    AccountManagement.TokenType
1>    AccountManagement.DeviceType
1>    AccountManagement.FreeFieldDefinition
1>    AccountManagement.IAccountManagementService
1>    AccountManagement.IAccountManagementServiceChannel
1>    AccountManagement.AccountManagementServiceClient
1>    EML.AuthDelegatingHandler
1>    EML.Extension
1>    EML.Members
1>    EML.Authenticated
1>    EML.FunctionAppConfiguration
1>    EML.Models.AuthToken
1>    EML.Models.Account
1>    EML.Models.AccountStatus
1>    EML.Models.ProgramDTO
1>    EML.Models.ClientDTO
1>    EML.Models.CompanyDTO
1>    EML.Models.UserPermissions
1>    EML.Models.ProgramPermission
1>    EML.Models.UserType
1>    EML.Models.EMLRole
1>    EML.Models.ClientRole
1>    EML.Models.ProgramRole
1>    EML.Models.ProgramTypes
1>    EML.Models.ClientUser
1>    EML.Models.EMLUser
1>    EML.Models.EML
1>    EML.Models.Client
1>    EML.Models.Program
1>    EML.Models.Company
1>    EML.Models.Card
1>    EML.Models.CardHolder
1>    EML.Handlers.BatchesCommandHandler
1>    EML.Handlers.HelloWorldCommandHandler
1>    EML.Handlers.PermissionsCommandHandler
1>    EML.Handlers.ProgramsCommandHandler
1>    EML.Handlers.UserPermissionsCommandHandler
1>    EML.Commands.BatchesCommand
1>    EML.Commands.HelloWorldCommand
1>    EML.Commands.ICommand`2
1>    EML.Commands.PermissionsCommand
1>    EML.Commands.ProgramsCommand
1>    EML.Commands.UserPermissionsCommand
1>    AccountManagement.AccountManagementServiceClient+EndpointConfiguration
1>    EML.AuthDelegatingHandler+<SendAsync>d__0
1>    EML.Authenticated+<AuthTokenAsync>d__5
1>    EML.Authenticated+<>o__6
1>    EML.Authenticated+<>c
1>    EML.FunctionAppConfiguration+<>c
1>    EML.Handlers.BatchesCommandHandler+<ExecuteAsync>d__0
1>    EML.Handlers.PermissionsCommandHandler+<ExecuteAsync>d__0
1>    null type in ReflectionTypeLoadException
1>With errors:
1>    FileLoadException: Could not load file or assembly 'Microsoft.Azure.DocumentDB.Core, Version=2.1.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621)
1>
1>   at FunctionMonkey.ConfigurationLocator.FindConfiguration(Assembly assembly) in /Users/jamesrandall/code/myOpenSource/functionMonkey/Source/FunctionMonkey/ConfigurationLocator.cs:line 115
1>   at FunctionMonkey.Compiler.Implementation.FunctionCompiler.Compile() in /Users/jamesrandall/code/myOpenSource/functionMonkey/Source/FunctionMonkey.Compiler/Implementation/FunctionCompiler.cs:line 64
1>   at FunctionMonkey.Compiler.Program.Main(String[] args) in /Users/jamesrandall/code/myOpenSource/functionMonkey/Source/FunctionMonkey.Compiler/Program.cs:line 47
1>C:\Users\melgs\.nuget\packages\functionmonkey.compiler\0.18.7-beta000\build\netstandard1.0\FunctionMonkey.Compiler.targets(21,5): error MSB3073: The command "dotnet "C:\Users\melgs\.nuget\packages\functionmonkey.compiler\0.18.7-beta000\build\netstandard1.0\..\..\tools\netcoreapp2.1/FunctionMonkey.Compiler.dll" "C:\GIT\myAzureFunction\EML\EML\bin\Debug\netcoreapp2.1\bin\EML.dll" --netcore21" exited with code -532462766.
1>Done building project "EML.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 1 up-to-date, 0 skipped ==========

**Comment by nugosu** [comment]
close
