### ISSUE TITLE
KeyVaultClient suggestion

### ISSUE THREAD

**Issue by sparkitny** [JamesRandall/FunctionMonkey#73]
Hi James,

I tried to integrate `KeyVaultClient` (`Microsoft.Azure.KeyVault`) to read secrets/certificates from a Key Vault in the `Startup.cs`:
````
var azureServiceTokenProvider = new AzureServiceTokenProvider();
var keyVaultClient = new KeyVaultClient(
    new KeyVaultClient.AuthenticationCallback(azureServiceTokenProvider.KeyVaultTokenCallback));
````
It's in the startup, because I need to setup `HttpClient` with a private certificate from a Key Vault via `HttpClientFactory`. That's the reason I tried Startup function `public void Build(IFunctionHostBuilder builder)`, as there I need to inject the `HttpClient`'s

At compile time I get:
````
Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'Microsoft.Azure.Services.AppAuthentication, Version=1.0.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621)
2>   at blablabla.Functions.Startup.Build(IFunctionHostBuilder builder)
2>   at FunctionMonkey.Compiler.Implementation.FunctionCompiler.Compile() in D:\wip\myOpenSource\functionMonkey\Source\FunctionMonkey.Compiler\Implementation\FunctionCompiler.cs:line 69
2>   at FunctionMonkey.Compiler.Program.Main(String[] args) in D:\wip\myOpenSource\functionMonkey\Source\FunctionMonkey.Compiler\Program.cs:line 47
2>C:\Users\me\.nuget\packages\functionmonkey.compiler\2.2.2\build\netstandard1.0\FunctionMonkey.Compiler.targets(21,5): error MSB3073: The command "dotnet "C:\Users\me\.nuget\packages\functionmonkey.compiler\2.2.2\build\netstandard1.0\..\..\tools\netcoreapp2.1/FunctionMonkey.Compiler.dll" "C:\Users\me\source\repos\blablabla\src\Web.Functions\bin\Debug\netcoreapp2.1\bin\blablabla.Application.Functions.dll" --netcore21" exited with code -532462766.
2>Done building project "Application.Functions.csproj" -- FAILED.
```

Do you have any suggestions?

**Comment by vip32** [comment]
@sparkitny  still relevant?

**Comment by sparkitny** [comment]
Hi @vip32, @JamesRandall,

it's not relevant anymore. I.e. it had nothing to do with the HttpClient nor the HttpClientFactory. The problem was, that I also had some WCF stuff that isn't compatible yet with net standard. I close this ticket. 

Thanks @vip32
