### ISSUE TITLE
Could not load file or assembly "Newtonsoft.Json"

### ISSUE THREAD

**Issue by adam-short** [JamesRandall/FunctionMonkey#8]
Hello again!
It appears the compiler is playing up again. At this point, I have finished coding the system and have gone to start my debugging & testing.

It was compiling and working fine right up until I reference Netwonsoft throughout some models to make sure the JSON Serialisation process succeeded correctly (well, it could have happened before then, but that was the latest change before I attempted to build it again).

Then, when I went to run unit tests, I get:
```
Microsoft (R) Build Engine version 15.7.179.6572 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 73.91 ms for /Users/adamshort/Desktop/Code/collaboro/ice/ICE/ICE.csproj.
Services/Implementations/TableService.cs(44,37): warning CS0168: The variable 'ex' is declared but never used [/Users/adamshort/Desktop/Code/collaboro/ice/ICE/ICE.csproj]
  ICE -> /Users/adamshort/Desktop/Code/collaboro/ice/ICE/bin/Debug/netstandard2.0/bin/ICE.dll
  
  Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. The system cannot find the file specified.
  
     at System.ModuleHandle.ResolveType(RuntimeModule module, Int32 typeToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount, ObjectHandleOnStack type)
     at System.ModuleHandle.ResolveTypeHandleInternal(RuntimeModule module, Int32 typeToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
     at System.Reflection.RuntimeModule.ResolveType(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments)
     at System.Reflection.CustomAttribute.FilterCustomAttributeRecord(CustomAttributeRecord caRecord, MetadataImport scope, Assembly& lastAptcaOkAssembly, RuntimeModule decoratedModule, MetadataToken decoratedToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, Object[] attributes, IList derivedAttributes, RuntimeType& attributeType, IRuntimeMethodInfo& ctor, Boolean& ctorHasParameters, Boolean& isVarArg)
     at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType, Boolean mustBeInheritable, IList derivedAttributes, Boolean isDecoratedTargetSecurityTransparent)
     at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimePropertyInfo property, RuntimeType caType)
     at System.Attribute.InternalGetCustomAttributes(PropertyInfo element, Type type, Boolean inherit)
     at System.Attribute.GetCustomAttribute(MemberInfo element, Type attributeType, Boolean inherit)
     at System.Reflection.CustomAttributeExtensions.GetCustomAttribute[T](MemberInfo element)
     at FunctionMonkey.Infrastructure.PostBuildPatcher.<>c.<ExtractPossibleQueryParameters>b__3_0(PropertyInfo x) in D:\wip\myOpenSource\functionMonkey\Source\FunctionMonkey\Infrastructure\PostBuildPatcher.cs:line 95
     at System.Linq.Enumerable.WhereSelectArrayIterator`2.ToArray()
     at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
     at FunctionMonkey.Infrastructure.PostBuildPatcher.ExtractPossibleQueryParameters(HttpFunctionDefinition httpFunctionDefinition1) in D:\wip\myOpenSource\functionMonkey\Source\FunctionMonkey\Infrastructure\PostBuildPatcher.cs:line 92
     at FunctionMonkey.Infrastructure.PostBuildPatcher.Patch(FunctionHostBuilder builder, String newAssemblyNamespace) in D:\wip\myOpenSource\functionMonkey\Source\FunctionMonkey\Infrastructure\PostBuildPatcher.cs:line 54
     at FunctionMonkey.Compiler.Implementation.FunctionCompiler.Compile() in D:\wip\myOpenSource\functionMonkey\Source\FunctionMonkey.Compiler\Implementation\FunctionCompiler.cs:line 67
     at FunctionMonkey.Compiler.Program.Main(String[] args) in D:\wip\myOpenSource\functionMonkey\Source\FunctionMonkey.Compiler\Program.cs:line 45
  /var/folders/ws/8qmgsd2d5qzgk18kqcr5tgb80000gn/T/tmpa999974e51404dffa5791cf067b9a5e3.exec.cmd: line 2: 91716 Abort trap: 6           dotnet "/Users/adamshort/.nuget/packages/functionmonkey.compiler/0.12.1-beta000/build/netstandard1.0/../../tools/netcoreapp2.0/FunctionMonkey.Compiler.dll" "/Users/adamshort/Desktop/Code/collaboro/ice/ICE/bin/Debug/netstandard2.0/bin/ICE.dll"
/Users/adamshort/.nuget/packages/functionmonkey.compiler/0.12.1-beta000/build/netstandard1.0/FunctionMonkey.Compiler.targets(11,5): error MSB3073: The command "dotnet "/Users/adamshort/.nuget/packages/functionmonkey.compiler/0.12.1-beta000/build/netstandard1.0/../../tools/netcoreapp2.0/FunctionMonkey.Compiler.dll" "/Users/adamshort/Desktop/Code/collaboro/ice/ICE/bin/Debug/netstandard2.0/bin/ICE.dll"" exited with code 134. [/Users/adamshort/Desktop/Code/collaboro/ice/ICE/ICE.csproj]

Build FAILED.

Services/Implementations/TableService.cs(44,37): warning CS0168: The variable 'ex' is declared but never used [/Users/adamshort/Desktop/Code/collaboro/ice/ICE/ICE.csproj]
/Users/adamshort/.nuget/packages/functionmonkey.compiler/0.12.1-beta000/build/netstandard1.0/FunctionMonkey.Compiler.targets(11,5): error MSB3073: The command "dotnet "/Users/adamshort/.nuget/packages/functionmonkey.compiler/0.12.1-beta000/build/netstandard1.0/../../tools/netcoreapp2.0/FunctionMonkey.Compiler.dll" "/Users/adamshort/Desktop/Code/collaboro/ice/ICE/bin/Debug/netstandard2.0/bin/ICE.dll"" exited with code 134. [/Users/adamshort/Desktop/Code/collaboro/ice/ICE/ICE.csproj]
    1 Warning(s)
    1 Error(s)

Time Elapsed 00:00:07.96
```
Which is a gleefully large error message that seems to be just saying that it can't find Newtonsoft.

Which is troubling, as I have 11.0.2 installed across the platform and it is referenced from multiple dependencies as well. I have tried clearing the bin & obj, restoring, reinstalling Newtonsoft, downgrading Newtonsoft, ect...

But with no success.

Let me know if there are any other details you require, 
Cheers,
Adam.

**Comment by adam-short** [comment]
I have narrowed it down a bit - the error seems to appear if I use JsonProperty on an ICommand-implementing class (in my case, AddTenantToPolicyCommand.cs) as followed:
```
using AzureFromTheTrenches.Commanding.Abstractions;
using ICE.Models;
using Newtonsoft.Json;

namespace ICE.Commands.Policies
{
    public class AddTenantToPolicyCommand : ICommand<Policy>
    {
        [JsonProperty("name")] // Commenting this out stops the error.
        public string PolicyName { get; set; }
        
        // [JsonProperty("newTenant")]
        public int NewTenant { get; set; }
    }
}
```
I have a sneaking suspicion that this has something to do with the way JSON serialisation & deserialisation is done natively by FM?

**Comment by adam-short** [comment]
Or, if a command subclasses from a class with JsonProperties.

**Comment by JamesRandall** [comment]
Apologies - struggled to find any time the last couple of days but almost certainly will over the weekend.

**Comment by JamesRandall** [comment]
Could you give this a go on the latest Azure Functions runtime with Function Monkey v0.13 please and let me know how you get on?

I'm struggling to replicate it but my attempts to do so have taken place after updating Function Monkey to be compatible with the new runtime.

**Comment by adam-short** [comment]
Yep will do - currently doing some spring cleaning on the codebase but I should get around to this in 3-4hrs.

**Comment by adam-short** [comment]
I can, in fact, confirm this isn't happening anymore. Weird, perhaps due to the new AZ function runtime?

**Comment by JamesRandall** [comment]
Yes I think so - I'd suspected it might be. They've done a lot of work around the dependency compatibility issues caused by things being in process and packages in the core runtime in the last couple of releases and the last update made the final set of changes for v2. It was super easy to get into a pickle before.

Phew.

Thanks for reporting and working through with me, much appreciated.

**Comment by davidjsteele** [comment]
Hi James, 
This seems to have reared its head again.  Using FM 3.0.17 with Microsoft.NET.sdk.Functions 1.0.30-beta2 results in :

`13>Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621)
13>   at System.ModuleHandle.ResolveType(RuntimeModule module, Int32 typeToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount, ObjectHandleOnStack type)
13>   at System.ModuleHandle.ResolveTypeHandleInternal(RuntimeModule module, Int32 typeToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
13>   at System.Reflection.RuntimeModule.ResolveType(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments)
13>   at System.Reflection.CustomAttribute.FilterCustomAttributeRecord(CustomAttributeRecord caRecord, MetadataImport scope, Assembly& lastAptcaOkAssembly, RuntimeModule decoratedModule, MetadataToken decoratedToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, Object[] attributes, IList derivedAttributes, RuntimeType& attributeType, IRuntimeMethodInfo& ctor, Boolean& ctorHasParameters, Boolean& isVarArg)
13>   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType, Boolean mustBeInheritable, IList derivedAttributes)
13>   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimePropertyInfo property, RuntimeType caType)
13>   at System.Attribute.InternalGetCustomAttributes(PropertyInfo element, Type type, Boolean inherit)`
