### ISSUE TITLE
FunctionMonkey.Compiler compilation error

### ISSUE THREAD

**Issue by KarachentsevDanil** [JamesRandall/FunctionMonkey#81]
Hi, James, for FM version 3.0.11-beta5 when you use arrays in commands you get the compilation error.
public class GetItemsByIdsQuery : ICommand<IActionResult>
    {
        public List<string> Ids { get; set; } = new List<string>();
    }

 Unhandled Exception: FunctionMonkey.ConfigurationException: CS0117:'string' does not contain a definition for 'TryParse' SourceFile(GetServicesByIds.cs[4720..4728))
     at FunctionMonkey.Compiler.Implementation.AssemblyCompiler.CompileAssembly(IReadOnlyCollection`1 syntaxTrees, IReadOnlyCollection`1 externalAssemblyLocations, OpenApiOutputModel openApiOutputModel, String outputBinaryFolder, String outputAssemblyName, String assemblyNamespace, TargetEnum target)
     at FunctionMonkey.Compiler.Implementation.FunctionCompiler.Compile() in /Users/jamesrandall/code/myOpenSource/functionMonkey/Source/FunctionMonkey.Compiler/Implementation/FunctionCompiler.cs:line 86
     at FunctionMonkey.Compiler.Program.Main(String[] args) in /Users/jamesrandall/code/myOpenSource/functionMonkey/Source/FunctionMonkey.Compiler/Program.cs:line 47

**Comment by JamesRandall** [comment]
The current release only works on typed arrays e.g. int[] and generic collections e.g. List<string> or IReadOnlyCollection<string>.

I'll look at adding support for the above in a point release.

**Comment by KarachentsevDanil** [comment]
> The current release only works on typed arrays e.g. int[] and generic collections e.g. List or IReadOnlyCollection.
> 
> I'll look at adding support for the above in a point release.

public List'<string'> Ids { get; set; } = new List'<string'>();

**Comment by JamesRandall** [comment]
Oh, that's interesting. Let me take a look!
